-- Update questions SQL (do not clear results on startup)
DELETE FROM questions;

INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('What is the average of first five multiples of 3?', '9', '12', '15', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A sum of money at simple interest amounts to Rs. 815 in 3 years. What is the principal?', 'Rs. 600', 'Rs. 650', 'Rs. 700', 3, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The cost price of 20 articles is the same as the selling price of x articles. If the profit is 25%, then the value of x is:', '15', '16', '18', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A train 120m long passes a pole in 6 seconds. What is its speed?', '60 km/hr', '72 km/hr', '80 km/hr', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('What is 15% of 200?', '20', '30', '40', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The ratio of ages of A and B is 4:5. If the sum of their ages is 36, find A age.', '16', '20', '18', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If a person sells an item for Rs. 120 and makes a 20% profit, what was the cost price?', '90', '100', '110', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Find the surface area of a cube whose side is 3cm.', '27', '36', '54', 3, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A work can be done by 8 men in 10 days. How many days will 10 men take?', '6', '8', '12', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('What is the square root of 1225?', '25', '35', '45', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Look at this series: 2, 1, (1/2), (1/4), ... What number should come next?', '(1/3)', '(1/8)', '(1/16)', 2, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If PALE is coded as 2134, what is the code for LEAP?', '4321', '3412', '3421', 3, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Pointing to a photograph, a man said, I have no brother or sister but that mans father is my fathers son. Whose photograph was it?', 'His own', 'His son', 'His father', 2, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Which word does NOT belong with the others?', 'Leopard', 'Cougar', 'Elephant', 3, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Find the missing number in the sequence: 3, 7, 15, 31, 63, ?', '95', '111', '127', 3, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If South-East becomes North, North-East becomes West and so on. What will West become?', 'South-East', 'North-East', 'South-West', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Cup is to Lip as Bird is to?', 'Bush', 'Beak', 'Wing', 2, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A is the mother of B and C. If D is the husband of C, what is A to D?', 'Mother', 'Aunt', 'Mother-in-law', 3, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Complete the series: SCD, TEF, UGH, ____, WKL', 'VIJ', 'VJT', 'UJI', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('In a certain code, COMPUTER is written as RFUVQNPC. How is MEDICINE written?', 'EOJDJEFM', 'EOJDEJFM', 'MFEJDJOE', 2, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If x/2 = 8, then x = ?', '16', '4', '32', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The area of a rectangle with length 5m and breadth 3m is:', '8 sq.m', '15 sq.m', '10 sq.m', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('10 - 3 * 2 = ?', '4', '14', '1', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The volume of a cube with side 4cm is:', '16 cu.cm', '64 cu.cm', '48 cu.cm', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If the profit is 20% and cost price is Rs. 100, selling price is:', 'Rs. 80', 'Rs. 120', 'Rs. 100', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('What is 25% of 160?', '40', '50', '60', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A bike travels 60km in 2 hours. What is its speed?', '30 km/hr', '120 km/hr', '15 km/hr', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The perimeter of a square with side 5m is:', '10m', '20m', '25m', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If 2x + 3 = 9, then x = ?', '2', '3', '6', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The average of 5, 10, 15 is:', '10', '15', '20', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A discount of 10% on Rs. 500 is:', 'Rs. 450', 'Rs. 50', 'Rs. 550', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If 3:5 = 9:x, then x = ?', '12', '15', '18', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('10 squared equals:', '20', '100', '50', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The simple interest on Rs. 1000 at 5% per annum for 2 years is:', 'Rs. 100', 'Rs. 50', 'Rs. 200', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If a = 2 and b = 3, then 2a + b = ?', '7', '8', '6', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The LCM of 12 and 18 is:', '24', '36', '48', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The GCD of 20 and 30 is:', '5', '10', '15', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If 40% of x = 80, then x = ?', '100', '200', '150', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The circumference of a circle with radius 7cm is:', '22 cm', '44 cm', '14 cm', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A train covers 300km in 5 hours. Its speed is:', '60 km/hr', '50 km/hr', '75 km/hr', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('12 / 3 + 2 = ?', '6', '4', '2', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If cost price is Rs. 50 and selling price is Rs. 60, profit % is:', '20%', '10%', '50%', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The diagonal of a square with side 4m is:', '4√2 m', '8 m', '16 m', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Find 5% of 500:', '25', '50', '75', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If 2x = 10, then x = ?', '5', '20', '2', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The area of a triangle with base 6 and height 4 is:', '12 sq.units', '24 sq.units', '10 sq.units', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('50 + 50 - 25 = ?', '75', '50', '100', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A watch costs Rs. 500 and is sold at 15% profit. Selling price is:', 'Rs. 575', 'Rs. 575', 'Rs. 425', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The average of 2, 4, 6, 8, 10 is:', '6', '8', '5', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If HCF(15, 25) = 5, then LCM(15, 25) = ?', '75', '150', '100', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A man walks 5km in 1 hour. At this rate, how far can he walk in 3 hours?', '15 km', '10 km', '20 km', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The compound interest on Rs. 1000 at 10% per annum for 1 year is:', 'Rs. 100', 'Rs. 110', 'Rs. 1100', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If x + 5 = 12, then x = ?', '7', '17', '2', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('15 * 2 - 10 = ?', '20', '30', '25', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The ratio 2:3 is equivalent to:', '4:6', '3:4', '6:9', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A shirt cost Rs. 200, now sold for Rs. 150. Loss % is:', '25%', '20%', '15%', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If 3x - 2 = 7, then x = ?', '3', '4', '5', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The square root of 144 is:', '12', '14', '10', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A car travels at 80 km/hr for 2.5 hours. Distance covered:', '200 km', '150 km', '250 km', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('30% of 300 is:', '90', '100', '120', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If 4x = 20, then x = ?', '5', '10', '4', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The area of a circle with radius 3.5cm is:', '38.5 sq.cm', '77 sq.cm', '42 sq.cm', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('18 / 3 * 2 = ?', '12', '3', '6', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If principal is Rs. 500 and rate is 8% p.a. for 3 years, SI is:', 'Rs. 120', 'Rs. 150', 'Rs. 100', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A number increased by 25% gives 125. The number is:', '100', '150', '50', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If -5 + 10 - 3 = x, then x = ?', '2', '8', '-8', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The perimeter of a rectangle 10m x 5m is:', '30 m', '50 m', '25 m', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('35% of 1000 is:', '350', '450', '300', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Find the next number: 1, 2, 4, 8, 16, ?', '24', '32', '20', 2, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If CAT is coded as 3-1-20, what is DOG coded as?', '4-15-7', '4-15-8', '3-14-6', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Which of the following is odd?', 'Triangle', 'Square', 'Circle', 3, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A is the father of B. B is the son of C. A is married to C. What is B to C?', 'Son', 'Daughter', 'Grandson', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If North becomes East, then West becomes:', 'South', 'North', 'East', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Book is to Author as Statue is to:', 'Artist', 'Stone', 'Museum', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Complete the pattern: AB, CD, EF, GH, ?', 'IJ', 'HI', 'JK', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If APPLE is coded as 1-16-16-12-5, what is FRUIT?', '6-18-21-9-20', '5-17-20-8-19', '7-19-22-10-21', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('All birds have wings. Sparrow is a bird. Therefore, Sparrow:', 'has wings', 'can fly', 'is brown', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Which number is missing in the series: 5, 10, 20, 40, ?', '80', '50', '60', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Shoes are to Feet as Hats are to:', 'Hair', 'Head', 'Face', 2, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If KING is coded as 11-9-14-7, then QUEEN is:', '17-21-5-5-14', '16-19-9-15-6', '12-10-13-8-15', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Which is different: Red, Blue, Green, Sweet', 'Sweet', 'Red', 'Blue', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A woman walks 5km North, then 5km East, then 5km South. Where is she?', '5km East of start', 'At start', '5km West', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If A > B and B > C, then:', 'A > C', 'A < C', 'A = C', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Doctor is to Hospital as Teacher is to:', 'Classroom', 'School', 'Student', 2, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Find the odd word: Red, Green, Blue, Table', 'Table', 'Red', 'Green', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('In a sequence 2, 5, 10, 17, 26, the next number is:', '37', '35', '40', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Thumb is to Hand as Toe is to:', 'Foot', 'Leg', 'Body', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If CHAIR is 5 letters, TABLE is 5 letters, then BOOK is:', '3 letters', '4 letters', '5 letters', 2, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Pointing to a man, a woman said: "His mother is my mothers only daughter". Who is the man to the woman?', 'Son', 'Brother', 'Grandson', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Which number replaces the question mark: 3, 6, 12, 24, ?', '48', '36', '30', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Water flows in Pipe. Pipe is made of:', 'Iron', 'Metal', 'Material', 3, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If AB12 is to CD34, then EF56 is to:', 'GH78', 'GH68', 'FH78', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A room has only one window and no lights are on. A man enters and sits in a dark corner. How does he see?', 'It is day time', 'He has torch', 'He has night vision', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Five brothers are born exactly one year apart. The youngest is 4. What is the age of the eldest?', '8 years', '9 years', '10 years', 2, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If PEN is to PENCIL as CAR is to:', 'CARPET', 'CARP', 'CARRIAGE', 3, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Find the missing: XAY, ZBW, CDV, ?', 'EFU', 'DEU', 'FGU', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A, B, C, D, E are 5 people. A is taller than B. C is shorter than D. E is taller than A. Who is tallest?', 'E', 'D', 'C', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If 2 days ago was Monday, what day will it be in 3 days?', 'Saturday', 'Friday', 'Sunday', 3, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Dentist is to Tooth as Surgeon is to:', 'Hospital', 'Body', 'Disease', 2, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Find the next in sequence: 1, 4, 9, 16, 25, ?', '36', '49', '64', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('All cats are animals. Fluffy is a cat. Therefore, Fluffy is:', 'an animal', 'cute', 'furry', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If first day is Monday and first date is 1st, then what day is 8th?', 'Monday', 'Tuesday', 'Sunday', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Key is to Lock as Light is to:', 'Dark', 'Switch', 'Bulb', 2, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Find the odd: 121, 144, 169, 195, 196', '195', '144', '121', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If SUNDAY is coded as 19-21-14-4-1-25, then MONDAY is:', '13-15-14-4-1-25', '12-14-13-5-2-26', '14-16-15-5-2-26', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A man leaves home heading East. After some time he turns left (North) then turns left again (West). He then turns left again and heads South. Where will he end up?', 'East of home', 'West of home', 'At home', 3, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Daughter of my brother is my:', 'Sister', 'Niece', 'Cousin', 2, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Complete: 1, 1, 2, 3, 5, 8, 13, ?', '21', '20', '19', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Which is the odd one: Apple, Mango, Carrot, Orange', 'Carrot', 'Apple', 'Mango', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If ABC = 3, DEFG = 4, then HIJKLMN = ?', '7', '8', '9', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Father of my father is my:', 'Grandfather', 'Uncle', 'Grandfather', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Which letter comes next: A, C, E, G, I, K, ?', 'M', 'L', 'N', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If + means *, * means /, / means - and - means +, then 10 + 5 * 2 - 3 / 2 = ?', '20', '15', '25', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('All metals are elements. Gold is a metal. Therefore, gold is:', 'an element', 'yellow', 'precious', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Clockwise from North: North, East, South, West, then comes:', 'North', 'South', 'East', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('Find the pattern: 2Z5, 3Y6, 4X7, 5W8, ?', '6V9', '5V8', '7V9', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('If STAR is to RATS, then LOOP is to:', 'POOL', 'PLLO', 'POOL', 1, 'REASONING');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A man is facing North. He turns right 90 degrees, then left 90 degrees. Now he is facing:', 'East', 'North', 'West', 2, 'REASONING');

INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('What is the average of first five multiples of 3?', '9', '12', '15', 1, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A sum of money at simple interest amounts to Rs. 815 in 3 years. What is the principal?', 'Rs. 600', 'Rs. 650', 'Rs. 700', 3, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('The cost price of 20 articles is the same as the selling price of x articles. If the profit is 25%, then the value of x is:', '15', '16', '18', 2, 'APTITUDE');
INSERT INTO questions (title, optionA, optionB, optionC, ans, category) VALUES ('A train 120m long passes a pole in 6 seconds. What is its speed?', '60 km/hr', '72 km/hr', '80 km/hr', 2, 'APTITUDE');